### ISSUE TITLE
搜索API报错

### ISSUE THREAD

**Issue by WoXueHouDeHenNe** [moztl/Restful-Api-Tool#12]
IDEA：2024.1

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.mozt.plugins.restful.a.d.a.e' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.mozt.plugins.restful]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by moztl** [comment]
感谢反馈，将会在下个版本修复该问题。

**Comment by moztl** [comment]
最新版本已修复该问题，一并修复 2024.1 的其他兼容问题，审核通过后可在 IDEA 插件市场中下载更新，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.25
